sudo: isrequired
services:
  - docker

before_install:
  - docker build -t ishan84/multiconapp-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ishan84/multiconapp-test npm test -- --coverage

after_success:
  - docker build -t ishan84/multiconapp-client ./client
  - docker build -t ishan84/multiconapp-nginx ./nginx
  - docker build -t ishan84/multiconapp-server ./server
  - docker build -t ishan84/multiconapp-worker ./worker

  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ishan84/multiconapp-client
  - docker push ishan84/multiconapp-nginx
  - docker push ishan84/multiconapp-server
  - docker push ishan84/multiconapp-worker